// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package handlers

import (
	"BankAccount/handlers"
	"BankAccount/repositories/implementations"
	"gorm.io/gorm"
)

// Injectors from CreateBankAccountHandler.go:

func CreateBankAccountHandler(dbConn *gorm.DB) (*handlers.BankAccountHandler, error) {
	iAccountRepository := implementations.NewAccountRepository(dbConn)
	bankAccountHandler := handlers.NewBankAccountHandler(iAccountRepository)
	return bankAccountHandler, nil
}

// Injectors from CreateBankAccountsHandler.go:

func CreateBankAccountsHandler(dbConn *gorm.DB) (*handlers.BankAccountsHandler, error) {
	iAccountRepository := implementations.NewAccountRepository(dbConn)
	bankAccountsHandler := handlers.NewBankAccountsHandler(iAccountRepository)
	return bankAccountsHandler, nil
}
